### PR TITLE
New/firstscenetick

### PR DESCRIPTION
**Pull request by pelgerr**
Add method to determine the first tick of a new scene

### CODE REVIEW

**Comment by brettchalupa** [comment]
@pelgerr thanks for this PR and the other one! I'm planning to check it out and review it in the coming days. Will give it a test and in-depth review soon.

**Comment by pelgerr** [comment]
@brettchalupa No problem. I've been chatting with f_3r on Discord about this, as my understanding was they were more or less carrying this torch while you took a step back for a while. I had mentioned that I've been using and lightly extending Scale and they recommended I open a few PRs. 

I'm still fairly inexperienced so I welcome all feedback and correction!

**Comment by brettchalupa** [comment]
@pelgerr I'm happy to help review PRs here on GitHub and support the project. 😄

**Review by brettchalupa — APPROVED** [review]
Makes sense to me!

**Pull request merged**
